db:
  config:
    timeout: 1000
    idleTimeout: 3600000
    maxLifetime: 4000000
    dataSouceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    maximumPoolSize: 30
    connectionTestQuery: select 1;
    #jdbc:mysql://172.16.116.148:3306/?user=common_admin
  dbs:
    - url: jdbc:mysql://172.16.116.148:3306/common_uuid?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      user: common_pro
      password: uHi7jzKtDnVpfaDy
      name: common_uuidMaster
    - url: jdbc:mysql://172.16.116.149:3306/common_uuid?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      user: common_pro
      password: uHi7jzKtDnVpfaDy
      name: common_uuidSlave
    - url: jdbc:mysql://172.16.100.121:3306/ucenter_statistic_and_log?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      user: entbase_pro
      password: sU6megDd;P3
      name: logDb
#spring:
#  redis:
#    host: 172.16.116.195
#    port: 6380
#    password: WXh19nfv
#auth:
#  redis:
#    host: 172.16.116.195
#    port: 6380
#    password: WXh19nfv
spring:
  redis:
    host: 172.16.116.148
#    host: 127.0.0.1
    port: 9736
    password: Ucenter@2019
    #password: shawnRedisForTest-1121
auth:
  redis:
#    host: 127.0.0.1
    host: 172.16.116.148
    port: 9736
    password: Ucenter@2019
    #password: shawnRedisForTest-1121
cache:
  redis:
    host: 172.16.116.4
    port: 20000
    password: uuid|OVL9hPVnkx