spring:
  datasource:
    url: jdbc:mysql://172.16.117.226:3306/uuid_job?useUnicode=true&characterEncoding=UTF-8
    username: ent_all
    password: ent
    driver-class-name: com.mysql.jdbc.Driver

#datasource.type=org.apache.tomcat.jdbc.pool.DataSource
  #datasource.tomcat.max-wait=10000
  #datasource.tomcat.max-active=30
  #datasource.tomcat.test-on-borrow=true
  #datasource.tomcat.validation-query=SELECT 1
  #datasource.tomcat.validation-interval=30000