### xxl-job email
spring:
  mail:
    host: smtp.263.net
    port: 8011
    username: ent@sunlands.com
    password: qiyejia2015
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory

### xxl-job, access token
xxl:
  job:
    accessToken:
### xxl-job, i18n (default empty as chinese, "en" as english)
    i18n:
## xxl-job, triggerpool max size
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
### xxl-job, log retention days
    logretentiondays: 30